import { Inter } from "next/font/google";
import "./globals.css";
import CrmContextProvider from "../../context/crm/provider";
import ToolContextProvider from "../../context/tools/provider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import initTranslations from "../i18n";
import { AlertContextProvider } from "../../context/common/AlertContext";
import { ModalAlert } from "../../components/modalAlert/ModalAlert";
import TranslationsProvider from "../../components/Providers/TranslationsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Easywork",
  description: "Generated by create next app",
};

const i18nNamespaces = [
  "contacts",
  "common",
  "tools",
  "auth",
  "leads",
  "users",
  "control",
  "operations",
];
export default async function RootLayout({ children, params: { locale } }) {
  const { resources } = await initTranslations(locale, i18nNamespaces);
  return (
    <html lang={locale} className="h-full">
      <body className={inter.className}>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <AlertContextProvider>
            <CrmContextProvider>
              <ToolContextProvider>
                <ToastContainer stacked />
                {children}
              </ToolContextProvider>
            </CrmContextProvider>
          </AlertContextProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
