name: "CI and PR Merge"

on:
  pull_request:
    branches:
      - development # Solo para PRs hacia la rama development

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm # Habilita el cache para pnpm

      - name: Ensure .next/cache directory exists
        run: mkdir -p .next/cache

      - name: Ensure ~/.pnpm-store directory exists
        run: mkdir -p ~/.pnpm-store

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install dependencies with pnpm
        run: pnpm install --shamefully-hoist --no-frozen-lockfile

      - name: Restore Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Build the application with pnpm
        run: pnpm build

  merge:
    runs-on: ubuntu-latest
    needs: build # Solo se ejecuta si el build fue exitoso
    if: ${{ needs.build.result == 'success' }} # Solo si el build fue exitoso

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Try to merge the Pull Request
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true # Continua sin error si la fusión falla

      - name: Notify PR author of merge failure
        if: failure()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ The automatic merge has failed. Please review the conflicts and try again."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send success notification
        if: success()
        run: echo "✅ Merge successful for PR \#${{ github.event.pull_request.number }}"
