name: CI for PRs

on:
  pull_request:
    branches:
      - development # Solo se ejecuta cuando se hace PR a la rama 'development'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

  merge:
    runs-on: ubuntu-latest
    needs: build # Solo se ejecuta si el build fue exitoso
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Try to merge the Pull Request
        id: merge
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check if merge failed
        if: failure()
        run: echo "Merge failed!"

      - name: Notify PR author of merge failure
        if: failure()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ The automatic merge has failed. Please review the conflicts and try again."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
